// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unbqgzgqigyzvdzxkdyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuYnFnemdxaWd5enZkenhrZHlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzEyMTksImV4cCI6MjA2ODkwNzIxOX0.QAN5DNAPFWr1iPAGN3GLPWtUInMD_iX3BNOrQcAylA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});